### ISSUE TITLE
The current file is not a SourcePawn script.

### ISSUE THREAD

**Issue by ZBzibing** [Sarrus1/sourcepawn-studio#408]
# Basic informations

- WIN10 22H2 19045.4412 [Windows]
- **VSCode version:** 1.90.2
- **Extension version:** 8.02

Compile file:
The current file is not a SourcePawn script.

**Comment by maxijabase** [comment]
This happens when you freshly open VSCode and the program hasn't realized you're actually stepping on a SourcePawn file. Selecting a couple files back and forth fixes the issue, that is, if you're actually on a valid .sp file.
The extension should not do this actually, we should find a way to force it to select an open document if there's one already opened.

**Comment by ZBzibing** [comment]
I don't know why this is happening, at least it wasn't before he updated it, I've completed hundreds of SPs with him, and many more excellent SP author docs that won't compile, all I want to do now is uninstall it and find the previous version to use!

**Comment by ZBzibing** [comment]
Solution.
Upgrade the compiler to
sourcemod-1.11.0-git6952

**Comment by Sarrus1** [comment]
I thanks for reporting this.
I don't think updating the compiler is the fix you are looking for.

**Comment by ZBzibing** [comment]
You can try using a lower version of 1.11, which will still report errors

**Comment by Spyro-Dragon** [comment]
Ive gotten this issue before. What fixed it for me is unchecking "Main Path Compilation"

**Comment by Sarrus1** [comment]
Closing this by making the error message detail which file is trying to be compiled. This should point the user in the right direction.
Feel free to reopen to discuss this further.

**Comment by ProfessorFartsalot** [comment]
> Closing this by making the error message detail which file is trying to be compiled. This should point the user in the right direction. Feel free to reopen to discuss this further.

Just had the same issue, had to uncheck Main Path Compilation to fix it.
