### ISSUE TITLE
Include "include/<subdir>/include" not found.

### ISSUE THREAD

**Issue by wopox1337** [Sarrus1/sourcepawn-studio#409]
Include is not found in subdirectories

![image](https://github.com/Sarrus1/sourcepawn-studio/assets/18553678/fadd31de-c994-4468-987b-5d472ca31360)

**Comment by ChitoseRaame** [comment]
same issue

**Comment by Sarrus1** [comment]
Unfortunately, the extension will not scan for `.inl` files.
Only `.inc` or `.sp`.

Feel free to reopen to discuss this further.

**Comment by wopox1337** [comment]
@Sarrus1 
> the extension will not scan for `.inl` files
Why? Can you add ?

**Comment by Sarrus1** [comment]
As far as I know spcomp will only work with .inc or .sp files?

**Comment by wopox1337** [comment]
Actually any files can be included
